CREATE TABLE error_log (
    log_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    log_date       DATE,
    module_name    VARCHAR2(100),
    error_code     NUMBER,
    error_message  VARCHAR2(4000)
);

select * from error_log;

drop table error_log;


select * from orders where order_id = 500;
DECLARE
    l_error_code    NUMBER;
    l_error_message VARCHAR2(4000);
BEGIN

    UPDATE orders
       SET order_status = 'NEPOSTOJECI_STATUS'
     WHERE order_id = 500;

EXCEPTION
    WHEN OTHERS THEN

        l_error_code := SQLCODE;
        l_error_message := SQLERRM;

        INSERT INTO error_log
        (
            
            log_date,
            module_name,
            error_code,
            error_message
        )
        VALUES
        (
            
            SYSDATE,
            'update_order_status',
            l_error_code,
            l_error_message
        );

        commit;    
END;
/

